name: Test
on: [push, pull_request]
jobs:
  tsplot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.2'
    - run: go test -v ./tsplot/...
  tscli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.2'
    - run: go test -v ./tscli/...

