name: Test
on: [push, pull_request]
jobs:
  tsplot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.20'
    - run: make test

